apiVersion: v1
kind: Service
metadata:
  name: openmcp-portal
  namespace: openmcp
spec:
  selector:
    name: openmcp-portal
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30903
  type: NodePort